name: technical_assessment
description: "A Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl:

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  http: ^1.3.0
  path: ^1.9.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.2.2
  build_runner: ^2.4.11
  riverpod_lint:
  custom_lint:

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  generate: true

